################ English language ##################
[en]
languageName = "Eng"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ Español language ##################
[es]
languageName = "Esp"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2

################ Catalan language ##################
[cat]
languageName = "Cat"
languageCode = "ca-es"
contentDir = "content/catalan"
weight = 3
