############# Catalan navigation ##############

# main menu-cat
[[main]]
name = "Inici"
pageRef = "https://datamirai.github.io/website/ca/"
weight = 1

[[main]]
name = "Posts"
weight = 2

[[main]]
parent = "Posts"
name = "Tots els posts"
pageRef = "https://datamirai.github.io/website/ca/blog/"

[[main]]
parent = "Posts"
name = "Artícles"
pageRef = "https://datamirai.github.io/website/ca/blog/"

[[main]]
parent = "Posts"
name = "DataViz"
pageRef = "https://datamirai.github.io/website/ca/blog/"

[[main]]
name = "ReEstimando Blog"
pageRef = "https://datamirai.github.io/website/ca/categories/reestimando/"
weight = 3

[[main]]
name = "Nosaltres"
pageRef = "https://datamirai.github.io/website/ca/authors"
weight = 4


# footer menu-cat

[[footer]]
name = "Contacta'ns"
Url = "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ07B8Ih74MHYxRNI3JVhj38FftPkbnIsgTtpXrgoTblohjPMtB9Zaun3E9PPTUI9SV5nlX43v7n"
weight = 1

[[footer]]
name = "Nosaltres"
pageRef = "https://datamirai.github.io/website/ca/about"
weight = 2
