############# Español navigation ##############

# main menu

[[main]]
name = "Inicio"
pageRef = "/"
weight = 1

[[main]]
name = "Posts"
weight = 2

[[main]]
parent = "Posts"
name = "Todos los posts"
pageRef = "/blog"

[[main]]
parent = "Posts"
name = "Artículos"
pageRef = "/categories/art%C3%ADculo/"

[[main]]
parent = "Posts"
name = "DataViz"
pageRef = "/categories/data-visualization/"

[[main]]
name = "ReEstimando Blog"
pageRef = "/categories/reestimando/"
weight = 3

[[main]]
name = "Nosotros"
pageRef = "/authors"
weight = 4

# footer menu

[[footer]]
name = "Contáctanos"
Url = "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ07B8Ih74MHYxRNI3JVhj38FftPkbnIsgTtpXrgoTblohjPMtB9Zaun3E9PPTUI9SV5nlX43v7n"
weight = 1

[[footer]]
name = "Nosotros"
pageRef = "/about"
weight = 2

