############# Español navigation ##############

# main menu-esp
[[main]]
name = "Inicio"
pageRef = "/"
weight = 1

[[main]]
name = "Artículos"
pageRef = "/about"
weight = 2

[[main]]
name = "El Blog de ReEstimando"
pageRef = "/categories/reestimando/"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"


# footer menu-esp
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elementos"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Política de Privacidad"
pageRef = "/privacy-policy"
weight = 3
