############# English navigation ##############

# main menu

[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Posts"
weight = 2

[[main]]
parent = "Posts"
name = "All posts"
pageRef = "/blog"

[[main]]
parent = "Posts"
name = "Articles"
pageRef = "/blog"

[[main]]
parent = "Posts"
name = "DataViz"
pageRef = "/blog"

[[main]]
name = "ReEstimando Blog"
pageRef = "/categories/reestimando/"
weight = 3

[[main]]
name = "About"
pageRef = "/authors"
weight = 4


# footer menu
[[footer]]
name = "Contact"
Url = "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ07B8Ih74MHYxRNI3JVhj38FftPkbnIsgTtpXrgoTblohjPMtB9Zaun3E9PPTUI9SV5nlX43v7n"
weight = 1

[[footer]]
name = "About"
pageRef = "/authors"
weight = 2

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 3

[[footer]]
name = "Privacy policy"
pageRef = "/privacy-policy"
weight = 4