# defaultContentLanguageInSubdir must be true for this to work.

# Other languages redirects
# [[redirects]]
# from = '/fr/**'
# to = '/fr/404.html'
# status = 404

# Default language must be last.
[[redirects]]
from = '/en/**'
to = '/en/404.html'
status = 404

[[redirects]]
from = '/ca/**'
to = '/ca/404.html'
status = 404

[[redirects]]
from = '/**'
to = '/404.html'
status = 404

[[redirects]]
from = '/ca/website/ca/blog/'
to = '/website/ca/blog/'
status = 202

[[redirects]]
from = '/en/website/en/blog/'
to = '/website/en/blog/'
status = 202